# -*- coding: utf-8 -*-
"""outofbounds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aAHZN3whtTpa89swj2hrJDufsZHwwzx
"""

array = [1,2,3]
print(array[5])