# -*- coding: utf-8 -*-
"""CSC419-Assignment2-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzZ3DlX8CXM_Q7nyYvVz5q_e8RX8-fba
"""

string = "hello"
string[0] = 'H'
